name: "🎨 Design"
description: "디자인 요소 반영"
labels: ["Design"]
body:
  - type: textarea
    id: overview
    attributes:
      label: "📌 작업 개요"
      description: "어떤 디자인 요소를 추가하거나 수정하시나요?"
      placeholder: "예: 메인 화면 탭바 아이콘 교체 및 브랜드 컬러 적용"
    validations:
      required: true
  - type: textarea
    id: assets
    attributes:
      label: "🖼 관련 에셋"
      description: "추가하거나 변경할 에셋 정보를 적어주세요."
      placeholder: "예: ic_home_active.png, Assets.xcassets 내 AccentColor 수정 등"
  - type: textarea
    id: tasks
    attributes:
      label: "✅ 작업 내용"
      description: "할 일을 체크박스 형태로 작성해주세요."
      placeholder: "최대한 세분화 해서 적어주세요!"
    validations:
      required: true
  - type: textarea
    id: design-reference
    attributes:
      label: "🙋🏻 참고 자료 (디자인 가이드)"
      description: "피그마(Figma) 링크나 참고할 디자인 시안이 있다면 첨부해 주세요."
      placeholder: "Figma 링크 혹은 디자인 스크린샷 드래그"
